# Generated by Django 5.0.1 on 2024-02-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fruit name')),
                ('latin_name', models.CharField(max_length=200, verbose_name='Latin name')),
                ('season', models.CharField(max_length=120)),
                ('sun', models.CharField(max_length=120)),
                ('water', models.CharField(max_length=120)),
                ('soil', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Plant name')),
                ('latin_name', models.CharField(max_length=200, verbose_name='Latin name')),
                ('season', models.CharField(max_length=120)),
                ('sun', models.CharField(max_length=120)),
                ('water', models.CharField(max_length=120)),
                ('soil', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vegetable name')),
                ('latin_name', models.CharField(max_length=200, verbose_name='Latin name')),
                ('season', models.CharField(max_length=120)),
                ('sun', models.CharField(max_length=120)),
                ('water', models.CharField(max_length=120)),
                ('soil', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
