# Generated by Django 5.0.1 on 2024-02-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_remove_fruit_sun_remove_plant_sun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='sun',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='sun',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
